Bugfix and add Low Power Mode
TheThingsNetwork/arduino-node-lib pull request #12
Opened 2018-02-12 01:13 UTC by hallard

- Created Low Power Battery Monitor example enabling lora module sleep mode
- Added Hard reset of Lora module at startup (with IO pin)
- Fixed issue #9 
- Enable Low Power of Lora Module of other examples sketches

2018-02-12 01:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/arduino-node-lib?pullRequest=12) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/arduino-node-lib?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/arduino-node-lib?pullRequest=12) it.</sub>

2018-02-12 01:18 UTC, hallard commented
This new pull request #12 should fix your issue, just let me know

2018-02-12 10:10 UTC, johanstokking requested changes
Thanks @hallard !! Looks good. Few changes, mostly styling. I'd like to keep this repository clean and consistent.

2018-02-12 10:10 UTC, johanstokking commented on library.properties
> +version=2.0.3
We're bumping versions in the `master` branch after merging

2018-02-12 10:10 UTC, johanstokking commented on src/TheThingsNode.cpp
> +    //Serial.println(F("IPRESS"));
Remove if not used

2018-02-12 10:10 UTC, johanstokking commented on src/TheThingsNode.cpp
> +    if ( this->buttonPressed ) {
Formatting (spaces)

2018-02-12 10:10 UTC, johanstokking commented on src/TheThingsNode.cpp
> +  #ifdef TTN_LORA_RESET
Formatting (indentation)

2018-02-12 10:10 UTC, johanstokking commented on docs/TheThingsNode.md
> +Pay attention, this internal sleep method of the library does not put the Lora module (RN2483) into sleep mode and thus your node may consume 3mA even in sleep mode. You need to manually set the lora
Lora -> LoRa
lora -> LoRa

2018-02-12 10:10 UTC, johanstokking commented on examples/Basic/Basic.ino
> +  ttn.sleep( 60000 );
Formatting (spaces)

2018-02-12 10:10 UTC, johanstokking commented on examples/BatteryMonitorLPP/BatteryMonitorLPP.ino
> +  ttn.sleep( (uint32_t) (CONFIG_INTERVAL*1000) );
Formatting (spaces)

2018-02-12 10:10 UTC, johanstokking commented on examples/BatteryMonitorLPP/BatteryMonitorLPP.ino
> +// **********************************************************************************
Although useful, we're not using these headers in examples.

Please add the concerning comments in code, if necessary.

2018-02-12 10:10 UTC, johanstokking commented on docs/TheThingsNode.md
> +Pay attention, this internal sleep method of the library does not put the Lora module (RN2483) into sleep mode and thus your node may consume 3mA even in sleep mode. You need to manually set the lora
RN2483 can also be RN2903

2018-02-12 10:29 UTC, johanstokking commented on examples/BatteryMonitorLPP/BatteryMonitorLPP.ino
> +  ttn.sleep( CONFIG_INTERVAL*1000 );
I meant to say no spaces in the parentheses 😊

2018-02-13 13:57 UTC, johanstokking commented
Can you also fix the CI?

2018-02-13 15:11 UTC, hallard commented
I've done all modifications, travis should be fine on next check

2018-02-13 15:18 UTC, johanstokking commented
@hallard you're using the `wake()` and `sleep()` functions which are not in the referenced release for testing of `TheThingsNode`.

Please change .travis.yml#L14 to version `v2.5.6`

2018-02-13 15:50 UTC, hallard commented
It's done, sorry wrong comments
Requires TheThingsNode library 2.5.6
should be 
Requires TheThingsNetwork library 2.5.6

2018-02-13 16:18 UTC, johanstokking approved these changes

2018-02-13 16:18 UTC, merged

2018-02-13 16:33 UTC, johanstokking commented
Thanks, this is now part of https://github.com/TheThingsNetwork/arduino-node-lib/releases/tag/v2.0.5