Fixed blue LED bug with cayenne LPP device
TheThingsNetwork/arduino-node-lib pull request #17
Opened 2018-10-04 13:33 UTC by simmoinard

I had problems with my Things nodes (after several time, it freezes on fixed blue light). The problem has been solved on the forum (https://www.thethingsnetwork.org/forum/t/the-things-node-new-low-power-library-development/12521/144?u=simmoinard)
The "Basics.ino" file has been updated with a simple Delay(50), but not the "CayenneLPP.ino" ...

2018-10-04 13:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/arduino-node-lib?pullRequest=17) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/arduino-node-lib?pullRequest=17) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/arduino-node-lib?pullRequest=17) it.</sub>

2018-10-05 08:40 UTC, johanstokking requested changes
Thanks, good catch. Two minor code style things.

2018-10-05 08:40 UTC, johanstokking commented on examples/CayenneLPP/CayenneLPP.ino
> +  // and say bye bye to RN2983 sleep mode
Please remove comment. While you're at it, also on line 101.

2018-10-05 09:08 UTC, simmoinard commented
Done !

2018-10-05 11:15 UTC, johanstokking approved these changes

2018-10-05 11:15 UTC, johanstokking commented
Thanks!

2018-10-05 11:15 UTC, merged

2018-10-05 11:18 UTC, johanstokking commented
Released in https://github.com/TheThingsNetwork/arduino-node-lib/releases/tag/v2.0.7